// Add one entry per painting. To use a real photo, set `image` to a filename
// inside the images/ folder (e.g. "images/sunset-1.jpg"). Leave `image` as
// null to show a placeholder block until you have the photo ready.
//
// Title, year, medium, and size are parsed from each photo's filename in
// images/. To change a painting's details, rename its file in that folder
// using the same "Title, Year, Medium, Size.jpg" pattern.
//
// Paintings are displayed chronologically by year (see script.js) — order
// here doesn't matter for display, except consecutive same-`group` entries,
// which are always shown together as one row (using the earliest year among
// them to decide where that row falls chronologically).
const PAINTINGS = [
  {
    title: "Madrid",
    year: 2026,
    medium: "Acrylic and charcoal on canvas",
    size: "42 x 61.5 cm",
    image: "images/Madrid, 2026, Acrylic and charcoal on canvas · 42 x 61.5 cm.jpg",
    description: "",
  },
  {
    title: "Sleeping",
    year: 2025,
    medium: "Mixed media on canvas",
    size: "88 x 240 cm",
    image: "images/The long man, 2025, mixed media on canvas 69.5x88 cm.jpg",
    description: "",
  },
  {
    title: "Carbaros",
    year: 2026,
    medium: "Charcoal and ink on paper",
    size: "100 x 70 cm",
    image: "images/Carbaros, 2026, charcoal&ink on paper, 100x70.jpg",
    description: "",
  },
  {
    title: "Maya",
    year: 2026,
    medium: "Mixed media on canvas",
    size: "95 x 55 cm",
    image: "images/Maya, 2026, mixed media on canvas 95x55cm.jpg",
    description: "",
  },
  {
    title: "The Day Before the War",
    year: 2026,
    medium: "Acrylic on canvas",
    size: "142 x 95 cm",
    image: "images/The day before the war, 2026, acrylic on canvas 142x95.jpg",
    description: "",
  },
  {
    title: "Triptych 1",
    year: 2026,
    medium: "Mixed media on canvas",
    size: "69 x 50 cm",
    image: "images/Triptych1, 2026, mixed media on canvas,69x50 cm.jpg",
    description: "",
    group: "triptych",
  },
  {
    title: "Triptych 2",
    year: 2026,
    medium: "Mixed media on canvas",
    size: "69 x 50 cm",
    image: "images/Triptych 2, 2026, mixed media on canvas,69x50 cm.jpg",
    description: "",
    group: "triptych",
  },
  {
    title: "Triptych 3",
    year: 2026,
    medium: "Mixed media on canvas",
    size: "69 x 50 cm each",
    image: "images/Triptych 3, 2026, mixed media on canvas,69x50 cm each.jpg",
    description: "",
    group: "triptych",
  },
  {
    title: "Untitled",
    year: 2026,
    medium: "Charcoal on paper",
    size: "A4",
    image: "images/Untitled, 2026, charcoal on paper, A4.jpg",
    description: "",
  },
  {
    // NOTE: this file's name says 2026 / mixed media on canvas, but you
    // earlier told me this same painting (by content) was 2005 / Acrylic
    // on canvas. Using the filename's info per your request — let me know
    // which is right and I'll fix it.
    title: "Untitled",
    year: 2026,
    medium: "Mixed media on canvas",
    size: "142 x 95 cm",
    image: "images/Untitled, 2026, mixed media on canvas 142x95cm.jpg",
    description: "",
  },
  {
    title: "Untitled",
    year: 2026,
    medium: "Mixed media on canvas",
    size: "188 x 129 cm",
    image: "images/Untitled, 2026, mixed media on canvas 188x129.jpg",
    description: "",
  },
  {
    title: "Untitled",
    year: 2026,
    medium: "Mixed media on canvas",
    size: "69.5 x 45 cm",
    image: "images/Untitled, 2026, mixed media on canvas 69.5x45cm.jpg",
    description: "",
  },
  {
    title: "Untitled",
    year: 2026,
    medium: "Mixed media on canvas",
    size: "96 x 58 cm",
    image: "images/Untitled, 2026, mixed media on canvas 96x58.jpg",
    description: "",
  },
  {
    title: "Untitled",
    year: 2026,
    medium: "Mixed media on canvas",
    size: "96 x 61 cm",
    image: "images/Untitled, 2026, mixed media on canvas 96x61cm.jpg",
    description: "",
  },
  {
    title: "Untitled",
    year: 2025,
    medium: "Mixed media on canvas",
    size: "50 x 73 cm",
    image: "images/Untitled, 2025, mixed media on canvas 50x73.PNG",
    description: "",
  },
  {
    title: "Pickok",
    year: 2024,
    medium: "Mixed media on canvas",
    size: "100 x 240 cm",
    image: "images/Pickok, 2024, mixed media on canvas 100x240 cm.jpg",
    description: "",
  },
  {
    // Grouped together at your request — shown as one row.
    title: "Untitled",
    year: 2022,
    medium: "Mixed media on canvas",
    size: "100 x 240 cm",
    image: "images/untitled, 2022, mixed media on canvas 100x240cm.jpg",
    description: "",
    group: "trio-1",
  },
  {
    title: "Sleeping",
    year: 2022,
    medium: "Mixed media on canvas",
    size: "90 x 240 cm",
    image: "images/Sleeping, 2022, mixed media on canvas 90x240cm.jpg",
    description: "",
    group: "trio-1",
  },
  {
    title: "Untitled",
    year: 2022,
    medium: "Mixed media on canvas",
    size: "90 x 240 cm",
    image: "images/Untitled, 2022, mixed media on canvas 90x240cm.jpg",
    description: "",
    group: "trio-1",
  },
  {
    title: "The American Colony",
    year: 2025,
    medium: "Mixed media on canvas",
    size: "88 x 240 cm",
    image: "images/The American Colony, 2025, mixed media on canvas 88x240 cm.jpg",
    description: "",
  },
  {
    title: "Untitled",
    year: 2024,
    medium: "Mixed media on canvas",
    size: "100 x 240 cm",
    image: "images/Untitled, 2024, mixed media on canvas 100x240 cm.jpg",
    description: "",
  },
  {
    title: "Tiktok Milchama",
    year: 2025,
    medium: "Mixed media on canvas",
    size: "88 x 240 cm",
    image: "images/tiktok milchama, 2025, mixed media on canvas 88x240 cm.jpg",
    description: "",
  },
  {
    // Photo shows 2 canvases together, kept as one image per your request.
    title: "Sleeping",
    year: 2023,
    medium: "Mixed media on canvas",
    size: "90 x 240 cm",
    image: "images/Sleeping, 2023, mixed media on canvas 90x240cm.jpg",
    description: "",
  },
  {
    title: "Untitled",
    year: 2025,
    medium: "Acrylic on canvas",
    size: "52 x 70 cm",
    image: "images/Untitled, 2025, acrylic on canvas 52x70.jpg",
    description: "",
  },
  {
    title: "Sleeping",
    year: 2024,
    medium: "Mixed media on canvas",
    size: "50 x 70 cm",
    image: "images/Sleeping, 2024, mixed media on canvas 50x70cm.jpg",
    description: "",
  },
  {
    // Photo shows 2 canvases together, kept as one image per your request.
    title: "Sleeping",
    year: 2024,
    medium: "Mixed media on canvas",
    size: "90 x 240 cm",
    image: "images/Sleeping, 2024, mixed media on canvas 90x240cm.jpg",
    description: "",
  },
  {
    // Photo shows 4 separate A3 works together, kept as one image per your
    // request.
    title: "Untitled",
    year: 2025,
    medium: "Mixed media on paper",
    size: "A3",
    image: "images/Untitled, 2025, mixed media on paper A3.jpg",
    description: "",
  },
  {
    title: "Listening",
    year: 2024,
    medium: "Acrylic on canvas paper",
    size: "38 x 38 cm",
    image: "images/listening, 2024, acrylic on canva paper, 38x38 cm.jpg",
    description: "",
  },
  {
    title: "Untitled",
    year: 2025,
    medium: "Mixed media on plaid fabric",
    size: "200 x 190 cm",
    image: "images/untitled, 2025, mixed media on plaid fabric, 200x190cm.jpg",
    description: "",
  },
];
